# Node.js Backend
# Build the backend Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      cd backend
      npm install
      npm run build
    displayName: "npm install and build backend"

  - task: CopyFiles@2
    displayName: 'Copy deployment files'
    inputs:
      SourceFolder: 'backend'
      Contents: |
        dist/**
        node_modules/**
        package.json
        package-lock.json
        prisma/**
        .env.example
      TargetFolder: '$(Build.ArtifactStagingDirectory)/backend-deploy'

  - task: ArchiveFiles@2
    displayName: "Archive backend deployment files"
    inputs:
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/backend-deploy"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
