# Node.js Backend
# Build the backend Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: "20.x"
  workingDirectory: "backend"
  azureSubscription: "Azure subscription 1"
  backendAppName: "minicoder-service"

stages:
  - stage: Build
    displayName: "Build Backend"
    jobs:
      - job: BuildJob
        displayName: "Build Node.js Application"
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: $(nodeVersion)

          - script: |
              cd $(workingDirectory)
              npm ci
            displayName: "Install dependencies"

          - script: |
              cd $(workingDirectory)
              npm run build
              npx prisma generate
            displayName: "Install dependencies, build, and generate Prisma client"

          - task: ArchiveFiles@2
            displayName: "Archive backend files"
            inputs:
              rootFolderOrFile: "$(workingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/backend-$(Build.BuildId).zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish build artifacts"
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "backend-dist"

  # - stage: Deploy
  #   displayName: "Deploy Backend"
  #   dependsOn:
  #     - Build
  #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #   jobs:
  #     - deployment: DeployJob
  #       displayName: "Deploy to Azure"
  #       environment: "Production"
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - download: current
  #                 artifact: "backend-dist"
  #                 displayName: "Download build artifacts"

  #               - task: AzureWebApp@1
  #                 displayName: "Deploy to Azure Web App"
  #                 inputs:
  #                   azureSubscription: "$(azureSubscription)"
  #                   appType: "webAppLinux"
  #                   appName: "$(backendAppName)"
  #                   package: "$(Pipeline.Workspace)/backend-dist/backend-$(Build.BuildId).zip"
  #                   runtimeStack: "NODE|20-lts"
  #                   startUpCommand: "npm start"

  #               - script: |
  #                   echo "Backend deployment steps go here"
  #                   echo "Artifact location: $(Pipeline.Workspace)/backend-dist"
  #                   ls -la $(Pipeline.Workspace)/backend-dist/
  #                 displayName: "Placeholder deployment step"
