/**
 * Example commands for different languages.
 */
export const EXAMPLE_COMMANDS: Record<string, string[]> = {
  en: [
    "Create a working calculator with all basic operations",
    "Make an interactive animal quiz with 5 questions and scoring",
    "Build a color guessing game with random colors and points",
    "Create a simple drawing app with different colors and brush sizes",
    "Make a memory card game with flip animations",
    "Build a timer app with start, stop, and reset functions",
    "Create a to-do list with add, delete, and check-off features",
    "Make a dice rolling app with animations",
    "Build a simple piano with clickable keys that play sounds",
    "Create a word counter tool that counts characters and words",
    "Build a rock-paper-scissors game you can play against the computer",
    "Create a weather app that shows random weather and fun icons",
    "Build a digital birthday card you can customize and share",
    "Make a coin flipping app with animation and sound",
    "Create a matching pairs emoji game",
    "Build a countdown clock for your next birthday",
    "Make a multiplication practice quiz with a score at the end",
    "Build a random joke generator with fun emojis",
    "Create a mini traffic light simulation you can control",
    "Build a virtual pet that changes when you feed or play with it",
    "Create a musical drum pad with sound effects",
    "Make a quiz about space and planets",
    "Build a simple habit tracker with stars for each day",
    "Create a maze game with keyboard controls",
    "Build a Simon Says memory game with colors and sounds",
    "Make a custom name badge generator",
    "Create a flashcard app to practice new words",
    "Build a mini clock that shows the current time",
    "Make a fun spinner wheel for making choices",
    "Build a digital fidget spinner",
    "Create a digital scoreboard for any game",
    "Make a random compliment generator",
    "Build a fruit slicing game with mouse controls",
    "Create a treasure hunt map with clickable clues",
    "Build a simple music note player",
    "Make a custom emoji creator with drag and drop features",
    "Create a calendar where you can add notes to days",
    "Build a mini hangman game for guessing words",
    "Create a poll where users can vote on their favorite animal",
    "Build a breathing exercise app with calming animation",
    "Make a virtual snow globe you can shake",
    "Create a math flashcard game with instant feedback",
    "Build a days-until countdown for any holiday",
    "Create a spelling bee quiz with scoring",
    "Make a dancing robot animation you can control",
    "Build a digital drawing pad with an eraser",
    "Create a silly story generator",
    "Make a tic-tac-toe game you can play with a friend",
    "Build a recipe card generator for favorite foods",
    "Create a gratitude journal where you add happy moments",
    "Make a mini weather station with animated sun and clouds",
    "Build a joke teller with random joke button",
    "Create a fortune cookie app with positive messages",
    "Make a superhero name generator",
    "Build a sports scoreboard for any two teams",
    "Create a coin collection tracker",
    "Make a rainbow color mixer tool",
    "Build a number guessing game with hints",
    "Create a virtual aquarium with animated fish",
    "Make a bug race simulator with start and reset buttons",
    "Build a cat and mouse chase game",
    "Create a birthday countdown timer",
    "Make a basketball hoop shooting game",
    "Build a plant watering reminder tool",
    "Create a chore chart with stickers",
    "Make a daily mood tracker with smiley faces",
    "Build a pop quiz app about countries and capitals",
    "Create a virtual magic 8 ball",
    "Make a digital pet rock that changes expressions",
    "Build a weather guessing game",
    "Create a Simon-style color sequence memory game",
    "Make a bedtime routine checklist",
    "Build a multiplication bingo game",
    "Create a world clock showing different time zones",
    "Make a rock band soundboard with guitar and drums",
    "Build a spelling practice game with word hints",
    "Create a dance move randomizer",
    "Make a mini sudoku puzzle",
    "Build a fun fact generator about animals",
    "Create a drawing guessing game",
    "Make a superhero power randomizer",
    "Build a silly face generator with mix and match parts",
    "Create a cupcake decorator app",
    "Make a mini quiz about oceans and sea creatures",
    "Build a random art prompt generator",
    "Create a farm animal sounds board",
    "Make a coin toss prediction game",
    "Build a rainbow color picker tool",
    "Create a matching flags to countries game",
    "Make a musical xylophone you can play",
    "Build a digital sticker album",
    "Create a food emoji guessing game",
    "Make a temperature converter for Celsius and Fahrenheit",
    "Build a bug-catching game with a timer",
    "Create a playground designer with drag and drop features",
    "Make a random superhero costume generator",
    "Build a kindness challenge spinner",
    "Create a digital aquarium with growing fish",
    "Make a fun math puzzle game",
    "Build a constellation viewer for the night sky",
    "Create a fun animal dance party animation",
    "Make a clock with day/night background changes",
    "Build a memory game with animal sounds",
    "Create a fruit basket sorter game",
    "Make a virtual drum kit you can play with keyboard",
  ],
  de: [
    "Erstelle einen funktionierenden Taschenrechner mit allen Grundrechenarten",
    "Mache ein interaktives Tier-Quiz mit 5 Fragen und Punktesystem",
    "Baue ein Farbenratespiel mit zufälligen Farben und Punkten",
    "Erstelle eine einfache Zeichen-App mit verschiedenen Farben und Pinselgrößen",
    "Mache ein Memory-Kartenspiel mit Flip-Animationen",
    "Baue eine Timer-App mit Start-, Stopp- und Zurücksetzen-Funktionen",
    "Erstelle eine To-Do-Liste mit Hinzufügen, Löschen und Abhaken",
    "Mache eine Würfel-App mit Animationen",
    "Baue ein Klavier mit anklickbaren Tasten und Tönen",
    "Erstelle ein Wortzähler-Tool für Zeichen und Wörter",
    "Baue ein Schere-Stein-Papier-Spiel gegen den Computer",
    "Erstelle eine Wetter-App mit zufälligem Wetter und lustigen Icons",
    "Baue eine digitale Geburtstagskarte zum Anpassen und Teilen",
    "Mache eine Münzwurf-App mit Animation und Ton",
    "Erstelle ein Emoji-Paare-Memo-Spiel",
    "Baue einen Countdown bis zu deinem nächsten Geburtstag",
    "Mache ein Mathe-Quiz zum Üben der Einmaleins-Reihen mit Punktestand",
    "Baue einen Zufallswitz-Generator mit Emojis",
    "Erstelle eine Ampelsimulation zum Umschalten",
    "Baue ein virtuelles Haustier, das du füttern und bespielen kannst",
    "Erstelle ein Musik-Drumpad mit Soundeffekten",
    "Mache ein Quiz über Planeten und das Weltall",
    "Baue einen einfachen Habit-Tracker mit Sternchen für jeden Tag",
    "Erstelle ein Labyrinth-Spiel mit Tastatur-Steuerung",
    "Baue ein Simon Says-Spiel mit Farben und Tönen",
    "Erstelle einen Namensschild-Generator",
    "Mache eine Vokabelkarten-App zum Üben neuer Wörter",
    "Baue eine Mini-Uhr, die die aktuelle Zeit anzeigt",
    "Mache ein Glücksrad zum Entscheiden",
    "Baue einen digitalen Fidget Spinner",
    "Erstelle einen digitalen Punktezähler für Spiele",
    "Mache einen Komplimente-Generator",
    "Baue ein Früchte-Schneide-Spiel mit Maussteuerung",
    "Erstelle eine Schatzsuche mit klickbaren Hinweisen",
    "Baue einen Musiknoten-Player",
    "Erstelle einen Emoji-Generator mit Drag & Drop",
    "Baue einen Kalender, in den du Notizen eintragen kannst",
    "Erstelle ein Galgenmännchen-Spiel zum Wörter erraten",
    "Baue eine Umfrage-App über Lieblingstiere",
    "Mache eine Atemübung-App mit beruhigender Animation",
    "Baue eine virtuelle Schneekugel, die man schütteln kann",
    "Erstelle ein Mathe-Flashcard-Spiel mit Feedback",
    "Baue einen Feiertags-Countdown",
    "Erstelle ein Rechtschreibquiz mit Punkten",
    "Baue einen tanzenden Roboter mit Animation",
    "Mache ein digitales Malpad mit Radiergummi",
    "Erstelle einen lustigen Geschichten-Generator",
    "Baue ein Tic-Tac-Toe-Spiel für zwei Spieler",
    "Mache einen Rezeptkarten-Generator für Lieblingsgerichte",
    "Erstelle ein Dankbarkeitstagebuch für schöne Momente",
    "Baue eine Mini-Wetterstation mit animierter Sonne und Wolken",
    "Erstelle einen Witze-Erzähler mit Zufallswitz-Knopf",
    "Mache eine Glückskeks-App mit positiven Sprüchen",
    "Erstelle einen Superhelden-Namen-Generator",
    "Baue eine Sportanzeige für zwei Teams",
    "Erstelle einen Münzsammler-Tracker",
    "Baue einen Regenbogenfarben-Mixer",
    "Mache ein Zahlenratespiel mit Tipps",
    "Erstelle ein virtuelles Aquarium mit animierten Fischen",
    "Baue ein Käferrennen mit Start- und Reset-Knopf",
    "Erstelle ein Fang-die-Katze-Spiel",
    "Baue einen Geburtstags-Countdown",
    "Erstelle ein Basketballwurf-Spiel",
    "Baue eine Pflanzen-Gieß-Erinnerung",
    "Erstelle einen Aufgabenplaner mit Stickern",
    "Baue einen Stimmungs-Tracker mit Smileys",
    "Mache ein Länder-und-Hauptstädte-Quiz",
    "Erstelle eine virtuelle Zauberkugel",
    "Baue ein digitales Haustier-Felsen, der Grimassen schneidet",
    "Erstelle ein Wetterratespiel",
    "Mache ein Simon-Spiel mit Farben und Tönen",
    "Baue eine Schlafenszeit-Checkliste",
    "Erstelle ein Bingo-Spiel für das Einmaleins",
    "Mache eine Weltuhr mit verschiedenen Zeitzonen",
    "Baue ein Soundboard für eine Rockband mit Gitarre und Schlagzeug",
    "Erstelle ein Rechtschreibspiel mit Hinweisen",
    "Baue einen Tanzmove-Zufallsgenerator",
    "Mache ein Mini-Sudoku-Rätsel",
    "Erstelle einen Fakten-Generator über Tiere",
    "Baue ein Zeichen-und-Rate-Spiel",
    "Erstelle einen Superhelden-Kraft-Zufallsgenerator",
    "Baue einen Quatschgesicht-Generator mit witzigen Teilen",
    "Mache eine Cupcake-Deko-App",
    "Erstelle ein Meeres-Quiz mit Seetieren",
    "Baue einen Zufallsgenerator für Kunstideen",
    "Erstelle ein Bauernhof-Tier-Soundboard",
    "Mache ein Münzwurf-Vorhersage-Spiel",
    "Baue ein Regenbogen-Farbwähler-Tool",
    "Erstelle ein Spiel zum Zuordnen von Flaggen und Ländern",
    "Mache ein Musik-Xylophon zum Spielen",
    "Baue ein digitales Stickeralbum",
    "Erstelle ein Essens-Emoji-Rate-Spiel",
    "Mache einen Temperatur-Umrechner für Celsius und Fahrenheit",
    "Baue ein Käferfang-Spiel mit Timer",
    "Erstelle einen Spielplatz-Designer mit Drag & Drop",
    "Baue einen Superhelden-Kostüm-Zufallsgenerator",
    "Mache ein Freundlichkeitsrad zum Drehen",
    "Baue ein digitales Aquarium mit wachsenden Fischen",
    "Erstelle ein lustiges Mathe-Puzzle",
    "Baue einen Sternbild-Betrachter für den Nachthimmel",
    "Mache eine Tier-Tanzparty-Animation",
    "Baue eine Uhr mit Tag-/Nacht-Hintergrund",
    "Erstelle ein Memory-Spiel mit Tiergeräuschen",
    "Mache ein Früchtekorb-Sortierspiel",
    "Baue ein virtuelles Schlagzeug, das du mit der Tastatur spielst",
  ],
  es: [
    // Add Spanish examples if you support Spanish
  ],
  // ...add more languages as needed
};
