name: Build and Deploy Angular App

on:
  push:
    branches: [main]
    paths-ignore:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Add permissions for GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create environment files from templates
        run: |
          cp src/environments/environment.template.ts src/environments/environment.ts
          cp src/environments/environment.prod.template.ts src/environments/environment.prod.ts

      - name: Replace environment variables
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MAIN_PROMPT: ${{ secrets.MAIN_PROMPT }}
          OPENAI_FIX_INSTRUCTIONS: ${{ secrets.OPENAI_FIX_INSTRUCTIONS }}
        run: |
          # Use node to replace the placeholders properly
          node -e "
          const fs = require('fs');
          const apiKey = process.env.OPENAI_API_KEY || '';
          const mainPrompt = process.env.MAIN_PROMPT || '';
          const fixInstructions = process.env.OPENAI_FIX_INSTRUCTIONS || '';

          // Escape template literal content (handle backticks and dollar signs)
          function escapeTemplateLiteral(str) {
            return str.replace(/\\\\/g, '\\\\\\\\')
                     .replace(/\`/g, '\\\\\`')
                     .replace(/\\\$/g, '\\\\\\\$');
          }

          // Process environment.ts
          let envContent = fs.readFileSync('src/environments/environment.ts', 'utf8');
          envContent = envContent.replace('YOUR_OPENAI_API_KEY_HERE', escapeTemplateLiteral(apiKey));
          envContent = envContent.replace('YOUR_MAIN_PROMPT_HERE', escapeTemplateLiteral(mainPrompt));
          envContent = envContent.replace('YOUR_OPENAI_FIX_INSTRUCTIONS_HERE', escapeTemplateLiteral(fixInstructions));
          fs.writeFileSync('src/environments/environment.ts', envContent);

          // Process environment.prod.ts
          let prodContent = fs.readFileSync('src/environments/environment.prod.ts', 'utf8');
          prodContent = prodContent.replace('YOUR_OPENAI_API_KEY_HERE', escapeTemplateLiteral(apiKey));
          prodContent = prodContent.replace('YOUR_MAIN_PROMPT_HERE', escapeTemplateLiteral(mainPrompt));
          prodContent = prodContent.replace('YOUR_OPENAI_FIX_INSTRUCTIONS_HERE', escapeTemplateLiteral(fixInstructions));
          fs.writeFileSync('src/environments/environment.prod.ts', prodContent);
          "

      - name: Build Angular app for production
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Add CNAME file
        run: echo 'minicoder.app' > dist/mini-coder/CNAME

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/mini-coder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
